version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: install yarn
          command: |
            sudo apt update
            sudo apt install curl
            curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
            sudo apt install nodejs
            sudo apt install yarn
      - run:
          name: check yarn version
          command: |
            yarn --version
            node --version
            npm --version
      
