version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            echo "Checking yarn and npm..."
            mkdir test
            node --version
            npm -version
            yarn -version
      - run: echo "A first hello"
