version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: yarnpkg/dev:latest
    steps:
      - checkout
      - run:
          name: check yarn version
          command: yarn --version
