version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: install yarn
          command: 'sudo apt-get update && sudo apt-get install yarn'
      - run:
          name: check yarn version
          command: yarn -version
